import { Inter } from "next/font/google";

import '../public/css/HomePage.css'
import '../public/css/globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zona Colorado",
  description: "Generated by create next app",
  
};

// app/layout.tsx
import {Providers} from "./providers";

export default function RootLayout({children}) {
  return (
    <html lang="en" >
      <link rel="icon" href="/public/images/ZonaColorado.png" />
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}